
const andreKriterierType = {
  TIL_BESLUTTER: 'TIL_BESLUTTER',
  REGISTRER_PAPIRSOKNAD: 'PAPIRSOKNAD',
  UTBETALING_TIL_BRUKER: 'UTBETALING_TIL_BRUKER',
  SOKT_GRADERING: 'SOKT_GRADERING',
};

export default andreKriterierType;
