const andreKriterierType = {
    TIL_BESLUTTER: 'TIL_BESLUTTER',
    UTBETALING_TIL_BRUKER: 'UTBETALING_TIL_BRUKER',
    AARSKVANTUM: 'AARSKVANTUM',
    AVKLAR_MEDLEMSKAP: 'AVKLAR_MEDLEMSKAP',
    UTLANDSSAK: 'UTLANDSSAK',
    SELVSTENDIG_FRILANS: 'SELVSTENDIG_FRILANS',
    KOMBINERT: 'KOMBINERT',
    PAPIRSOKNAD: 'PAPIRSOKNAD',
    VURDER_OPPTJENINGSVILKÅRET: 'VURDER_OPPTJENINGSVILKÅRET',
    PAPIRSØKNAD: 'PAPIRSØKNAD',
    AVKLAR_ARBEIDSFORHOLD: 'AVKLAR_ARBEIDSFORHOLD',
};

export default andreKriterierType;
