
const behandlingType = {
  ANKE: 'BT-008',
  FORSTEGANGSSOKNAD: 'BT-002',
  INNSYN: 'BT-006',
  KLAGE: 'BT-003',
  REVURDERING: 'BT-004',
  AARSKVANTUM: 'AARSKVANTUM',
  AVKLAR_MEDLEMSKAP: 'AVKLAR_MEDLEMSKAP',

};

export default behandlingType;
