const behandlingType = {
  ANKE: 'BT-008',
  FORSTEGANGSSOKNAD: 'BT-002',
  INNSYN: 'BT-006',
  KLAGE: 'BT-003',
  REVURDERING: 'BT-004',
  TILBAKEBETALING: 'BT-007',
  PAPIRSØKNAD: 'PAPIRSØKNAD',
  PAPIRETTERSENDELSE: 'PAPIRETTERSENDELSE',
  PAPIRINNTEKTSOPPLYSNINGER: 'PAPIRINNTEKTSOPPLYSNINGER',
  DIGITAL_ETTERSENDELSE: 'DIGITAL_ETTERSENDELSE',
  INNLOGGET_CHAT: 'INNLOGGET_CHAT',
  SKRIV_TIL_OSS_SPØRMSÅL: 'SKRIV_TIL_OSS_SPØRMSÅL',
  SKRIV_TIL_OSS_SVAR: 'SRKIV_TIL_OSS_SVAR',
};

export default behandlingType;
