const behandlingType = {
  ANKE: 'BT-008',
  FORSTEGANGSSOKNAD: 'BT-002',
  INNSYN: 'BT-006',
  KLAGE: 'BT-003',
  REVURDERING: 'BT-004',
  TILBAKEBETALING: 'BT-007',
  PAPIRSØKNAD: 'PAPIRSØKNAD',
  PAPIRETTERSENDELSE: 'PAPIRETTERSENDELSE',
  PAPIRINNTEKTSOPPLYSNINGER: 'PAPIRINNTEKTSOPPLYSNINGER',
  DIGITAL_ETTERSENDELSE: 'DIGITAL_ETTERSENDELSE',
  INNLOGGET_CHAT: 'INNLOGGET_CHAT',
  SKRIV_TIL_OSS_SPØRMSÅL: 'SKRIV_TIL_OSS_SPØRMSÅL',
  SKRIV_TIL_OSS_SVAR: 'SKRIV_TIL_OSS_SVAR',
  SAMTALEREFERAT: 'SAMTALEREFERAT',
  KOPI: 'KOPI',
  UKJENT: 'UKJENT',
  INNTEKTSMELDING_UTGÅTT: 'INNTEKTSMELDING_UTGÅTT',
  UTEN_FNR_DNR: 'UTEN_FNR_DNR',
};

export default behandlingType;
