const fagsakYtelseType = {
  PLEIEPENGER_SYKT_BARN: 'PSB',
  OMSORGSPENGER: 'OMP',
  OMSORGSDAGER: 'OMD',
  OMSORGSDAGER_MIDLERTIDIGALENE: 'OMP_MA',
  OMSORGSDAGER_KRONISKSYK: 'OMP_KS',
  OMSORGSDAGER_ALENEOMOMSORGEN: 'OMP_AO',
  PUNSJ: 'PUNSJ',
  UKJENT: 'UKJENT',
  PPN: 'PPN',
};

export default fagsakYtelseType;
