const apiPaths = {
	aksjonspunkterPerEnhet: '/api/k9-los-api/avdelingsleder/nokkeltall/aksjonspunkter-per-enhet-historikk',
	allePaaVent: '/api/k9-los-api/avdelingsleder/nokkeltall/alle-paa-vent_v2',
	antallOppgaverIKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/antall`,
	antallOppgaverIKoV3UtenReserverte: (id: string) =>
		`/api/k9-los-api/ny-oppgavestyring/ko/${id}/antall-uten-reserverte`,
	avdelinglederReservasjoner: '/api/k9-los-api/avdelingsleder/reservasjoner',
	endreReservasjoner: '/api/k9-los-api/saksbehandler/oppgaver/reservasjon/endre',
	opphevReservasjoner: '/api/k9-los-api/saksbehandler/oppgaver/opphev',
	behandlede: '/api/k9-los-api/saksbehandler/oppgaver/behandlede',
	behandlingerUnderArbeid: '/api/k9-los-api/avdelingsleder/nokkeltall/behandlinger-under-arbeid',
	beholdningPerDato: '/api/k9-los-api/avdelingsleder/nokkeltall/beholdning-historikk',
	dagensTall: '/api/k9-los-api/avdelingsleder/nokkeltall/dagens-tall',
	driftsmeldinger: '/api/k9-los-api/driftsmeldinger',
	ferdigstilteHistorikk: '/api/k9-los-api/avdelingsleder/nokkeltall/ferdigstilte-historikk',
	hentAlleKoerSaksbehandlerV1: '/api/k9-los-api/saksbehandler/oppgaveko',
	hentAlleKoerSaksbehandlerV3: '/api/k9-los-api/ny-oppgavestyring/ko/saksbehandlerskoer',
	hentFelter: '/api/k9-los-api/ny-oppgavestyring/oppgave/felter',
	hentOppgaveFelter: '/api/k9-los-api/ny-oppgavestyring/oppgave/felter',
	hentOppgaveFraKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/fa-oppgave`,
	hentOppgaveko: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}`,
	hentOppgavekoer: '/api/k9-los-api/ny-oppgavestyring/ko/',
	hentOppgaver: '/api/k9-los-api/ny-oppgavestyring/oppgave/query',
	hentAntallOppgaver: '/api/k9-los-api/ny-oppgavestyring/oppgave/query/antall',
	hentOppgaverSomFil: '/api/k9-los-api/ny-oppgavestyring/oppgave/queryToFile',
	hentSaksbehandlereAvdelingsleder: '/api/k9-los-api/avdelingsleder/saksbehandlere',
	leggTilSaksbehandlerAvdelingsleder: '/api/k9-los-api/avdelingsleder/saksbehandlere/legg-til',
	hentSaksbehandlereSomSaksbehandler: '/api/k9-los-api/saksbehandler/oppgaver/saksbehandlere',
	hentSaksbehandlereIKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/saksbehandlere`,
	hentTiNesteIKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/oppgaver`,
	k9PunsjUrl: '/api/k9-los-api/konfig/k9-punsj-url',
	k9SakUrl: '/api/k9-los-api/konfig/k9-sak-url',
	kodeverk: '/api/k9-los-api/kodeverk',
	kopierOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko/kopier',
	legacyOppgaveKoer: '/api/k9-los-api/avdelingsleder/oppgavekoer',
	leggTilSaksbehandler: '/api/k9-los-api/ny-oppgavestyring/ko/saksbehandler',
	nyeFerdigstilteOppsummering: '/api/k9-los-api/avdelingsleder/nokkeltall/nye-ferdigstilte-oppsummering',
	nyeOgFerdigstilteOppgaver: '/api/k9-los-api/saksbehandler/nokkeltall/nye-og-ferdigstilte-oppgaver',
	nyePerDato: '/api/k9-los-api/avdelingsleder/nokkeltall/nye-historikk',
	oppdaterOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko',
	oppgaver: '/api/k9-los-api/saksbehandler/oppgaver/antall',
	oppgaverAntallTotalt: '/api/k9-los-api/avdelingsleder/oppgaver/antall-totalt',
	opprettOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko/opprett',
	reserverOppgave: '/api/k9-los-api/saksbehandler/oppgaver/reserver',
	refreshUrl: '/api/k9-los-api/konfig/refresh-url',
	saksbehandler: '/api/k9-los-api/saksbehandler',
	saksbehandlerNesteOppgaver: (id: string) => `/api/k9-los-api/saksbehandler/oppgaver?id=${id}`,
	saksbehandlerReservasjoner: '/api/k9-los-api/saksbehandler/oppgaver/reserverte',
	saksbehandlereIOppgaveko: '/api/k9-los-api/saksbehandler/oppgaveko/saksbehandlere',
	slettOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko/',
	slettSaksbehandler: '/api/k9-los-api/avdelingsleder/saksbehandlere/slett',
	sok: '/api/k9-los-api/fagsak/sok',
	sokV3: '/api/k9-los-api/ny-oppgavestyring/sok',
	validerQuery: '/api/k9-los-api/ny-oppgavestyring/oppgave/validate',
};

export default apiPaths;
