const apiPaths = {
	ferdigstilteHistorikk: '/api/avdelingsleder/nokkeltall/ferdigstilte-historikk',
	dagensTall: '/api/avdelingsleder/nokkeltall/dagens-tall',
	allePaaVent: '/api/avdelingsleder/nokkeltall/alle-paa-vent_v2',
	nyeOgFerdigstilteOppgaver: '/api/saksbehandler/nokkeltall/nye-og-ferdigstilte-oppgaver',
	behandlingerUnderArbeid: '/api/avdelingsleder/nokkeltall/behandlinger-under-arbeid',
	beholdningPerDato: '/api/avdelingsleder/nokkeltall/beholdning-historikk',
	nyePerDato: '/api/avdelingsleder/nokkeltall/nye-historikk',
	nyeFerdigstilteOppsummering: '/api/avdelingsleder/nokkeltall/nye-ferdigstilte-oppsummering',
	oppgaverAntallTotalt: '/api/avdelingsleder/oppgaver/antall-totalt',
	legacyOppgaveKoer: '/api/avdelingsleder/oppgavekoer',
	saksbehandler: '/api/saksbehandler',
	k9SakUrl: '/api/konfig/k9-sak-url',
	k9PunsjUrl: '/api/konfig/k9-punsj-url',
	refreshUrl: '/api/konfig/refresh-url',
	driftsmeldinger: '/api/driftsmeldinger',
	behandlede: '/api/saksbehandler/oppgaver/behandlede',
	kodeverk: '/api/kodeverk',
	aksjonspunkterPerEnhet: '/api/avdelingsleder/nokkeltall/aksjonspunkter-per-enhet-historikk',
	avdelinglederReservasjoner: '/api/avdelingsleder/reservasjoner',
	saksbehandlerReservasjoner: '/api/saksbehandler/oppgaver/reserverte',
	saksbehandlerOppgaver: '/api/saksbehandler/oppgaver',
	saksbehandlereIOppgaveko: '/api/saksbehandler/oppgaveko/saksbehandlere',
	oppgaver: '/api/saksbehandler/oppgaver/antall',
	oppgavekoer: '/api/saksbehandler/oppgaveko',
	sok: '/api/fagsak/sok',
	hentOppgaveko: '/api/ny-oppgavestyring/ko/',
	kopierOppgaveko: '/api/ny-oppgavestyring/ko/kopier',
	hentOppgavekoer: '/api/ny-oppgavestyring/ko/',
	opprettOppgaveko: '/api/ny-oppgavestyring/ko/opprett',
	oppdaterOppgaveko: '/api/ny-oppgavestyring/ko',
	slettOppgaveko: '/api/ny-oppgavestyring/ko/',
	hentSaksbehandlere: '/api/avdelingsleder/saksbehandlere',
	hentFelter: '/api/ny-oppgavestyring/oppgave/felter',
	hentOppgaver: '/api/ny-oppgavestyring/oppgave/query',
	valider: '/api/ny-oppgavestyring/oppgave/validate',
	hentOppgaveFelter: '/api/ny-oppgavestyring/oppgave/felter',
	hentOppgaverSomFil: '/api/ny-oppgavestyring/oppgave/queryToFile',
};

export default apiPaths;
