const apiPaths = {
	aksjonspunkterPerEnhet: '/api/avdelingsleder/nokkeltall/aksjonspunkter-per-enhet-historikk',
	allePaaVent: '/api/avdelingsleder/nokkeltall/alle-paa-vent_v2',
	antallOppgaverIKoV3: (id: string) => `/api/ny-oppgavestyring/ko/${id}/antall-oppgaver`,
	avdelinglederReservasjoner: '/api/avdelingsleder/reservasjoner',
	behandlede: '/api/saksbehandler/oppgaver/behandlede',
	behandlingerUnderArbeid: '/api/avdelingsleder/nokkeltall/behandlinger-under-arbeid',
	beholdningPerDato: '/api/avdelingsleder/nokkeltall/beholdning-historikk',
	dagensTall: '/api/avdelingsleder/nokkeltall/dagens-tall',
	driftsmeldinger: '/api/driftsmeldinger',
	ferdigstilteHistorikk: '/api/avdelingsleder/nokkeltall/ferdigstilte-historikk',
	hentAlleKoerSaksbehandlerV1: '/api/saksbehandler/oppgaveko',
	hentAlleKoerSaksbehandlerV3: '/api/ny-oppgavestyring/ko/saksbehandlerskoer',
	hentFelter: '/api/ny-oppgavestyring/oppgave/felter',
	hentOppgaveFelter: '/api/ny-oppgavestyring/oppgave/felter',
	hentOppgaveFraKoV3: (id: string) => `/api/ny-oppgavestyring/ko/${id}/fa-oppgave`,
	hentOppgaveko: (id: string) => `/api/ny-oppgavestyring/ko/${id}`,
	hentOppgavekoer: '/api/ny-oppgavestyring/ko/',
	hentOppgaver: '/api/ny-oppgavestyring/oppgave/query',
	hentOppgaverSomFil: '/api/ny-oppgavestyring/oppgave/queryToFile',
	hentSaksbehandlere: '/api/avdelingsleder/saksbehandlere',
	hentSaksbehandlereIKoV3: (id: string) => `/api/ny-oppgavestyring/ko/${id}/saksbehandlere`,
	hentTiNesteIKoV3: (id: string) => `/api/ny-oppgavestyring/ko/${id}/oppgaver`,
	k9PunsjUrl: '/api/konfig/k9-punsj-url',
	k9SakUrl: '/api/konfig/k9-sak-url',
	kodeverk: '/api/kodeverk',
	kopierOppgaveko: '/api/ny-oppgavestyring/ko/kopier',
	legacyOppgaveKoer: '/api/avdelingsleder/oppgavekoer',
	leggTilSaksbehandler: '/api/ny-oppgavestyring/ko/saksbehandler',
	nyeFerdigstilteOppsummering: '/api/avdelingsleder/nokkeltall/nye-ferdigstilte-oppsummering',
	nyeOgFerdigstilteOppgaver: '/api/saksbehandler/nokkeltall/nye-og-ferdigstilte-oppgaver',
	nyePerDato: '/api/avdelingsleder/nokkeltall/nye-historikk',
	oppdaterOppgaveko: '/api/ny-oppgavestyring/ko',
	oppgaver: '/api/saksbehandler/oppgaver/antall',
	oppgaverAntallTotalt: '/api/avdelingsleder/oppgaver/antall-totalt',
	opprettOppgaveko: '/api/ny-oppgavestyring/ko/opprett',
	refreshUrl: '/api/konfig/refresh-url',
	saksbehandler: '/api/saksbehandler',
	saksbehandlereIOppgaveko: '/api/saksbehandler/oppgaveko/saksbehandlere',
	saksbehandlerNesteOppgaver: (id: string) => `/api/saksbehandler/oppgaver?id=${id}`,
	saksbehandlerReservasjoner: '/api/saksbehandler/oppgaver/reserverte',
	slettOppgaveko: '/api/ny-oppgavestyring/ko/',
	sok: '/api/fagsak/sok',
	valider: '/api/ny-oppgavestyring/oppgave/validate',
};

export default apiPaths;
